### ISSUE TITLE
Adding total number of projects or a "Serial No" column to the Table on home page 

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgery#65]
Would it be convenient to have a total number of projects/packages on the [home page](https://github.com/UCL/scikit-surgery/wiki). Another way could be to add the serial number column to the table and on the glance one could find the total packages/projects.

@tdowrick @thompson318 @MattClarkson

**Comment by mianasbat** [comment]
Feel free to assign me to issues, if you guys think the issue make sense and needs changing!

**Comment by thompson318** [comment]
I'm not sure. It creates another maintenance task, and anyone wanting to know the total number can count them.

**Comment by mianasbat** [comment]
Okay it seems that it is not needed. So it can be closed.

@MattClarkson

**Comment by mxochicale** [comment]
Closed in favour of https://github.com/SciKit-Surgery/scikit-surgery-stats
